# Generated by Django 5.2.12 on 2026-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Код контрагента в 1С (например НФ-000580)",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
