# Generated by Django 5.2.12 on 2026-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_onec_string_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onec_register_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время успешного ответа create_counterparty",
                null=True,
                verbose_name="Контрагент создан в 1С",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="onec_register_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Текст последней ошибки create_counterparty (если была)",
                verbose_name="Ошибка выгрузки в 1С",
            ),
        ),
    ]
