# Generated by Django 5.2.12 on 2026-03-26 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_onec_register_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("retail", "Розница"),
                    ("wholesale", "Опт"),
                    ("manager", "Менеджер"),
                ],
                db_index=True,
                default="retail",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WholesaleUpgradeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Комментарий пользователя"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manager_note",
                    models.TextField(
                        blank=True, help_text="Комментарий менеджера при отказе"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_wholesale_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wholesale_upgrade_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на оптовый доступ",
                "verbose_name_plural": "Заявки на оптовый доступ",
                "ordering": ["-created_at"],
            },
        ),
    ]
