# Generated by Django 6.0.2 on 2026-03-25 07:20

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Address label (e.g., Home, Work)", max_length=100
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Дом"),
                            ("work", "Работа"),
                            ("other", "Другое"),
                        ],
                        default="home",
                        max_length=20,
                    ),
                ),
                (
                    "street_address",
                    models.CharField(help_text="Street address", max_length=255),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "state_province",
                    models.CharField(help_text="State/Province", max_length=100),
                ),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Kyrgyzstan", "Кыргызстан"),
                            ("Philippines", "Philippines"),
                            ("United States", "United States"),
                            ("Canada", "Canada"),
                            ("United Kingdom", "United Kingdom"),
                            ("Australia", "Australia"),
                            ("Japan", "Japan"),
                            ("South Korea", "South Korea"),
                            ("Singapore", "Singapore"),
                            ("Malaysia", "Malaysia"),
                            ("Thailand", "Thailand"),
                            ("Indonesia", "Indonesia"),
                            ("Vietnam", "Vietnam"),
                            ("India", "India"),
                            ("China", "China"),
                            ("Hong Kong", "Hong Kong"),
                            ("Taiwan", "Taiwan"),
                            ("Germany", "Germany"),
                            ("France", "France"),
                            ("Italy", "Italy"),
                            ("Spain", "Spain"),
                            ("Netherlands", "Netherlands"),
                            ("Belgium", "Belgium"),
                            ("Switzerland", "Switzerland"),
                            ("Austria", "Austria"),
                            ("Sweden", "Sweden"),
                            ("Norway", "Norway"),
                            ("Denmark", "Denmark"),
                            ("Finland", "Finland"),
                            ("Brazil", "Brazil"),
                            ("Mexico", "Mexico"),
                            ("Argentina", "Argentina"),
                            ("Chile", "Chile"),
                            ("Colombia", "Colombia"),
                            ("Peru", "Peru"),
                            ("New Zealand", "New Zealand"),
                            ("South Africa", "South Africa"),
                            ("United Arab Emirates", "United Arab Emirates"),
                            ("Saudi Arabia", "Saudi Arabia"),
                            ("Israel", "Israel"),
                            ("Turkey", "Turkey"),
                            ("Russia", "Russia"),
                            ("Other", "Other"),
                        ],
                        default="Kyrgyzstan",
                        max_length=100,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Set as default address"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Session key for anonymous carts",
                        max_length=40,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Customer name", max_length=100)),
                ("email", models.EmailField(help_text="Contact email", max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Общее"),
                            ("bug", "Ошибка"),
                            ("feature", "Предложение"),
                            ("complaint", "Жалоба"),
                            ("compliment", "Благодарность"),
                            ("other", "Другое"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Feedback subject", max_length=200),
                ),
                ("message", models.TextField(help_text="Feedback message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Не прочитано"),
                            ("read", "Прочитано"),
                            ("archived", "В архиве"),
                        ],
                        default="unread",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes for admins"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("payment_method", models.CharField(default="COD", max_length=20)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В обработке"),
                            ("out_for_delivery", "Передан в доставку"),
                            ("delivered", "Доставлен"),
                            ("returned", "Возврат"),
                            ("refunded", "Возврат средств"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the product name (auto-generated)",
                        max_length=250,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Акционная цена; если задана и ниже price — показывается она",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Количество на складе"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in grams (g)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Product dimensions (e.g., '21cm x 14.8cm')",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this product is available for purchase",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as featured product (shown on homepage)",
                    ),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(default=False, help_text="Mark as bestseller"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sale", "Продажа"),
                            ("restock", "Пополнение"),
                            ("adjustment", "Ручная корректировка"),
                            ("return", "Возврат"),
                            ("damaged", "Бой/потеря"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_change",
                    models.IntegerField(
                        help_text="Positive for additions, negative for deductions"
                    ),
                ),
                (
                    "stock_before",
                    models.PositiveIntegerField(
                        help_text="Stock quantity before this transaction"
                    ),
                ),
                (
                    "stock_after",
                    models.PositiveIntegerField(
                        help_text="Stock quantity after this transaction"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this transaction"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция по складу",
                "verbose_name_plural": "Операции по складу",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=shop.models.product_image_upload_path),
                ),
                ("alt", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house_address", models.CharField(blank=True, max_length=255)),
                (
                    "contact_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a profile picture",
                        null=True,
                        upload_to=shop.models.profile_picture_upload_path,
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[
                            ("KGS", "Кыргызский сом (с)"),
                            ("USD", "US Dollar ($)"),
                            ("RUB", "Российский рубль (₽)"),
                        ],
                        default="KGS",
                        help_text="Preferred currency for pricing",
                        max_length=3,
                    ),
                ),
                (
                    "preferred_payment_method",
                    models.CharField(
                        choices=[
                            ("COD", "Наличными при получении"),
                            ("CARD", "Банковская карта"),
                            ("ELWALLET", "Электронный кошелёк"),
                            ("BANK", "Банковский перевод"),
                        ],
                        default="COD",
                        help_text="Preferred payment method",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция в корзине",
                "verbose_name_plural": "Позиции в корзине",
                "unique_together": {("cart", "product")},
            },
        ),
    ]
