# Generated by Django 5.2.12 on 2026-03-26 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_fill_category_slugs"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="catalog_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_cart_items",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="shop.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("catalog_product__isnull", True), ("product__isnull", False)
                    ),
                    models.Q(
                        ("catalog_product__isnull", False), ("product__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="cartitem_shop_xor_catalog",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("cart", "product"),
                name="uniq_cartitem_shop_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("catalog_product__isnull", False)),
                fields=("cart", "catalog_product"),
                name="uniq_cartitem_catalog_product",
            ),
        ),
    ]
