# Generated by Django 6.0.4 on 2026-04-18 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_shipping_fee'),
        ('shop', '0004_promotion_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Товар в акции', 'verbose_name_plural': 'Акции: товары'},
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='catalog_order',
            field=models.ForeignKey(blank=True, help_text='Единый заказ (orders_order), если продажа с демо-витрины.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_inventory_transactions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Устаревший заказ shop_order (старые записи).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='shop.order'),
        ),
    ]
