# Generated by Django 6.0.4 on 2026-04-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_gallery_and_sku'),
        ('shop', '0005_alter_promotionitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Меньше — выше в списке (если сортировка на сайте позволяет)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='На сайте')),
                ('catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_arrival_entries', to='products.product', verbose_name='Товар каталога (1С)')),
                ('shop_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_arrival_entries', to='shop.product', verbose_name='Демо-товар витрины')),
            ],
            options={
                'verbose_name': 'Товар в новинках',
                'verbose_name_plural': 'Новинки: товары',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('catalog_product__isnull', False), ('shop_product__isnull', True)), models.Q(('catalog_product__isnull', True), ('shop_product__isnull', False)), _connector='OR'), name='shop_newarrivalitem_catalog_xor_shop_product'), models.UniqueConstraint(condition=models.Q(('catalog_product__isnull', False)), fields=('catalog_product',), name='shop_newarrivalitem_uniq_catalog_product'), models.UniqueConstraint(condition=models.Q(('shop_product__isnull', False)), fields=('shop_product',), name='shop_newarrivalitem_uniq_shop_product')],
            },
        ),
    ]
