# Generated by Django 6.0.4 on 2026-04-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_wishlist_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
