# Generated by Django 6.0.3 on 2026-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OneCInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Сайт → 1С"), ("inbound", "1С → сайт")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("endpoint", models.CharField(max_length=512)),
                ("method", models.CharField(default="POST", max_length=16)),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("payload_summary", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Лог 1С",
                "verbose_name_plural": "Логи 1С",
                "ordering": ["-created_at"],
            },
        ),
    ]
