# Generated by Django 6.0.3 on 2026-03-25 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID заказа в 1С (например ORDER-000124)",
                        max_length=120,
                        null=True,
                        unique=True,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(db_index=True, default="draft", max_length=64),
                ),
                (
                    "payment_status",
                    models.CharField(db_index=True, default="pending", max_length=64),
                ),
                (
                    "delivery_status",
                    models.CharField(db_index=True, default="pending", max_length=64),
                ),
                (
                    "payment_url",
                    models.URLField(blank=True, default="", max_length=2000),
                ),
                (
                    "payment_provider",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "payment_external_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("currency", models.CharField(default="KGS", max_length=8)),
                ("price_type", models.CharField(default="retail", max_length=20)),
                (
                    "warehouse_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "export_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_export_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.UUIDField(db_index=True)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "name_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Наименование на момент заказа (для 1С)",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
    ]
