# Generated by Django 5.2.12 on 2026-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
