# Generated by Django 6.0.4 on 2026-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_unify_delivery_and_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Доставка (для отображения; итог в total_amount).', max_digits=14),
        ),
    ]
