# Generated by Django 6.0.4 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_shipping_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("pickup", "Самовывоз"), ("courier", "Курьерская доставка")],
                db_index=True,
                default="pickup",
                help_text="Способ доставки клиента.",
                max_length=20,
            ),
        ),
    ]
