# Generated by Django 6.0.4 on 2026-04-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_delivery_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
