# Generated by Django 6.0.4 on 2026-04-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_delivery_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
