# Generated by Django 5.2.12 on 2026-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.CharField(
                editable=False, max_length=64, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.CharField(
                editable=False, max_length=64, primary_key=True, serialize=False
            ),
        ),
    ]
