# Generated by Django 5.2.12 on 2026-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_onec_string_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                help_text="ЧПУ для ссылок на сайте (генерируется из кода и названия 1С).",
                max_length=220,
                null=True,
                unique=True,
            ),
        ),
    ]
