# Generated by Django 5.2.12 on 2026-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_fill_category_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Фото на витрине и в карточке товара (если не загружено — показывается заглушка).",
                null=True,
                upload_to="products/catalog",
            ),
        ),
    ]
