# Generated by Django 5.2.12 on 2026-03-26 06:17

import django.db.models.deletion
import products.models
from django.db import migrations, models


def copy_legacy_product_images(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductImage = apps.get_model("products", "ProductImage")
    for p in Product.objects.exclude(image="").exclude(image__isnull=True):
        ProductImage.objects.create(
            product_id=p.pk,
            image=p.image,
            sort_order=0,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=products.models.product_gallery_upload_path
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Порядок слева направо (меньше — раньше)."
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото в галерее",
                "verbose_name_plural": "Галерея фото",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
        migrations.RunPython(copy_legacy_product_images, noop_reverse),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
